config/routes.rb
Rails.application.routes.draw do
  root "events#index"

  resources :events
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  validates :title, presence: true
  validates :venue, presence: true
  validates :location, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:notice] = "Event created!"
      redirect_to @event
    else
      flash.now[:alert] = "Event not created"
      render "new"
    end
  end

  def show
  end

  def index
    @events = Event.all
  end

  def edit
  end

  def update
    if @event.update(event_params)
      flash[:notice] = "Event Updated"
      redirect_to @event
    else
      flash.now[:alert] = "Event not Updated"
      render "edit"
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :start_date, :end_date, :venue, :location)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = " ")
    default_title = "Eventsboard - Create Events to Socialize"
    if page_title.empty?
      default_title
    else
      "#{page_title} | #{default_title}"
    end
  end

  def time_format(event_date)
    event_date.strftime("%A, %d %b %Y %l:%M %p")
  end
  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<% if event.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved: </h2>
    <ul>
      <%=event.errors.full_messages.each do |message|%>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(event) do |f| %>
<div>
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>
<div>
  <%= f.label :description %>
  <%= f.text_field :description%>
</div>
<div>
  <%= f.label :start_date %>
  <%= f.datetime_select(:start_date, order: [:day, :month, :year], start_year: Date.current.year, ampm: true, prompt: true) %>
</div>
<div>
  <%= f.label :end_date %>
  <%= f.datetime_select(:end_date, order: [:day, :month, :year], start_year: Date.current.year, ampm: true, prompt: true) %>
</div>
<div>
  <%= f.label :venue %>
  <%= f.text_field :venue %>
</div>
<div>
  <%= f.label :location %>
  <%= f.text_field :location %>
</div>

<%= f.submit %>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<h1> All Events </h1>

<p><%= link_to "Add Event", new_event_path %></p>

<%= @events.each do |event| %>
  <div>
    <h4><%= link_to event.title, event %></h4>
    <p><%= time_format(event.start_date) %></p>
    <p><%= time_format(event.end_date) %></p>
    <p><%= event.venue %></p>
    <p><%= event.location %></p>
  </div>
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<%= provide(:title, @event.title) %>

<h1> <%= @event.title %> </h1>

<div>
  <p><%= @event.description %> </p>

  <p><%= time_format(@event.start_date) %> </p>

  <p> <%= time_format(@event.end_date) %></p>

  <p> <%= @event.venue %> </p>

  <p> <%= @event.location %> </p>
</div>

<%= link_to "Edit Event", edit_event_path(@event) %>

<%= link_to "Delete Event", event_path(@event), method: :delete, data: {confirm: "Are you Sure?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>